baseurl: https://thenightshadenotebook.com
languageCode: en-us
title: The Nightshade Notebook
defaultContentLanguage: en
hasCJKLanguage: false
disqusShortname: thenightshadenotebook
pagination:
  pagerSize: 5
