baseurl: https://thenightshadenotebook.com
languageCode: en-us
title: The Nightshade Notebook
defaultContentLanguage: en
hasCJKLanguage: false
disqusShortname: hugo-theme-stack
pagination:
  pagerSize: 5
